[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build-preview"

[template.environment]
  STATUSKIT_PAGE_TITLE = "Graphcool Status"
  STATUSKIT_COMPANY_LOGO = ""
  STATUSKIT_SUPPORT_CONTACT_LINK = "https://slack.graph.cool"
  STATUSKIT_RESOURCES_LINK = "https://graph.cool/docs"
