baseurl = "/"
languageCode = "en-us"
title = "Graphcool Status"

[permalinks]
  incidents = "/incidents/:year/:month/:day/:slug/"

[params]
  defaultLogo = "/images/logo.svg"
  faviconsPath = "/images/favicon/"

# List of systems monitored in this status page.
# You'll be able to change their status every time
# you open or update an incident.
# Example:
# systems = ["API", "CDN", "DNS", "Site delivery"]
systems = [
  "Simple API",
  "Simple Subscriptions API",
  "Relay API",
  "System API",
  "Files API",
  "Images API",
  "Function Engine",
  "Console",
  "Homepage",
]
